#' Process Breakpoint Cut Files
#'
#' This function processes genomic cut files generated by BISCUT3 for specified models and genomes.
#' It reads the cut data, applies specified thresholds, and organizes the information into a unified
#' format suitable for analysis of arm-level aneuploidy.
#'
#' @param cuts.path A string representing the path to the cut file generated by BISCUT3.
#' @param cutoff A numeric value for the cutoff threshold (default is 0.98) used in processing.
#' @param model A character string specifying the model type (default is "human").
#' @param ref.path A string representing the path to an optional reference breakpoint file.
#' @param ref2.type A character string specifying the type of cancer for background reference.
#' @param genome A character string specifying the genome version (default is "hg38").
#' @param stringent A logical indicating whether to apply stringent criteria for merging segments (default is FALSE).
#'
#' @return A list containing:
#'         - `cuts`: A data frame with processed genomic cut data.
#'         - `tel_bound`: A data frame of telomere bounds.
#'         - `cent_bound`: A data frame of centromere bounds.
#'         - `amp`: A data frame of amplified segments.
#'         - `del`: A data frame of deleted segments.
#'
#' @export
#' @import dplyr
#' @import magrittr
#' @import stringr

processCuts <- function(cuts.path = NULL, ## The pathway to the breakpoint file produced from BISUCT3-py3 or from createCuts
                        cutoff = 0.98, ## Hard threshold to determine the amplification/ deletion of a segment
                        model = "human", ## Which organism you are using.
                        ref.path = NULL, ## The pathway to the breakpoint file used as supplement reference to your preferencce, or
                        ref2.type = NULL, ## You could tell us what cancer type you want to use as background to supplement the breakpoints
                        genome = "hg38", ## The genome your segmentation was build in
                        stringent = FALSE ## Whether to use stringent or lenient cutoff for the breakpoints
                        ) {


  ## Section 0: Goal Breakpoints to Achieve ------------------------------------
  data("breakpoints", package = "BAGEL")

  ## Section 1: User Breakpoints -----------------------------------------------
  if(!is.null(cuts.path)){
    cut <- loadCuts(cuts.path = cuts.path) # Select interested columns
    cuts <- stringentLenient(bpdf = cut, stringent = stringent) # Collapse by Arm and TelCent for lenient
    cuts$label <- "user"
    compiled <- cuts
  } else {
    compiled <- NULL
    warning("No Breakpoint File Provided, you should run BISCUT3-py3 first!")
  }

  ## Section 2: Reference Breakpoints ------------------------------------------
  ## Section 2.1: User provided supplement breakpoint
  if(!is.null(ref.path)){
    ref <- loadCuts(ref.path)
    ref <- stringentLenient(bpdf = ref, stringent = stringent) # Collapse by Arm and TelCent for lenient
    compared <- compareCuts(reference = ref, breakpoint = cuts, filename = "user_ref_compare")
    ref$label <- "user_ref"
    ref <- ref %>% dplyr::filter(! id %in% cuts$id)
    compiled <- rbind(compiled, ref)
  } else {
    warning("No Reference breakpoint file provided, we recommend you provide one.")
  }


  ## Section 2.2: User provided cancer type, use in house supplement from TCGA
  if(!is.null(ref2.type)){
    if(ref2.type == "bladder"){ ref2 <- BAGEL::bladder }
    if(ref2.type == "breast"){ ref2 <- BAGEL::breast }
    if(ref2.type == "colorectal"){ ref2 <- BAGEL::colorectal }
    if(ref2.type == "esophageal"){ ref2 <- BAGEL::esophageal }
    if(ref2.type == "glioblastoma"){ ref2 <- BAGEL::glioblastoma }
    if(ref2.type == "head_and_neck"){ ref2 <- BAGEL::head_and_neck }
    if(ref2.type == "kidney_clear_cell"){ ref2 <- BAGEL::kidney_clear_cell }
    if(ref2.type == "low_grade_glioma"){ ref2 <- BAGEL::low_grade_glioma }
    if(ref2.type == "ovarian"){ ref2 <- BAGEL::ovarian }
    if(ref2.type == "pancancer"){ ref2 <- BAGEL::pancancer }
    ref2 <- stringentLenient(bpdf = ref2, stringent = stringent)
    compared <- compareCuts(reference = ref2, breakpoint = cuts, filename = "supplement_ref")
    ref2$label <- "reference"
    ref2 <- ref2 %>% dplyr::filter(! id %in% compiled$id)
    compiled <- rbind(compiled, ref2)
  } else {
    warning("skip reference breakpoints, use hard thresholds.")
  }



  ## Section 3: Hard Threshold -------------------------------------------------
  message("using hard threshold of 0.98, like GISTIC2")
  if (model == "human") {
    if (genome == "hg38") {
      message("version: hg38"); ref3 <- QCtreeCNV::hg38_chr_arms
    } else if (genome == "hg19") {
      message("version: hg19"); ref3 <- QCtreeCNV::hg19_chr_arms
    }
  } else if (file.exists(genome)) {
    message(paste0("using customized reference for ", model)); ref3 <- read.delim(genome)
  } else {
    message("file not exist, exiting")
  }

  # Edit the reference dataset
  ref3$telcent <- "tel"
  ref3$label <- "hard_threshold"
  ref3_amp <- ref3_del <- ref3
  ref3_amp$direction <- "amp"
  ref3_del$direction <- "del"
  ref3_amp$id <- paste0(ref3_amp$arm_ID, "_", ref3_amp$telcent, "_", ref3_amp$direction)
  ref3_del$id <- paste0(ref3_del$arm_ID, "_", ref3_del$telcent, "_", ref3_del$direction)
  ref3 <- rbind(ref3_del, ref3_amp)
  ref3 <- ref3 %>% dplyr::select(arm_ID, telcent, direction, id, start, end, label) %>%
    dplyr::filter(!id %in% compiled$id) %>%
    as.data.frame()
  colnames(ref3) <- colnames(compiled)
  ref3 <- ref3 %>% mutate(largest_end = ifelse(grepl("p$", arm),
                                               cutoff * largest_end,
                                               largest_end),
                          smallest_start = ifelse(grepl("q$", arm) & !is.na(smallest_start),
                                                  smallest_start + (smallest_start * (1 - cutoff)),
                                                  smallest_start))
  ref3 <- ref3 %>% mutate(smallest_start = ifelse(grepl("p$", arm), largest_end * 0.98, smallest_start),
                        largest_end = ifelse(grepl("q$", arm), smallest_start * 1.02, largest_end))
  compiled <- rbind(compiled, ref3)


  ## Section 3: Formulate a unified cut file for cutting arm-level aneuploidy --------------------------
  message("----------Formulate a unified cut file for cutting arm-level aneuploidy-------------")

  # Separate telomere and centromere
  tel_bound <- compiled %>% dplyr::filter(telcent == "tel")
  cent_bound <- compiled %>% dplyr::filter(telcent == "cent")
  amp <- compiled %>% dplyr::filter(direction == "amp")
  del <- compiled %>% dplyr::filter(direction == "del")

  # Return a list
  return(list(cuts = compiled, tel_bound = tel_bound, cent_bound = cent_bound, amp = amp, del = del))
}





