#' Summarize BAGEL Analysis Output Files
#'
#' Provides a comprehensive summary of all output files generated by BAGEL analysis,
#' including file existence checks, file sizes, and organization by output type.
#' This function helps users verify that their analysis completed successfully and
#' understand what outputs are available.
#'
#' @param output_dir Character, path to the BAGEL analysis output directory
#' @param verbose Logical, whether to print detailed file information (default: TRUE)
#'
#' @return Invisibly returns a list containing:
#'   \item{total_files}{Number of total output files}
#'   \item{key_files_status}{Named logical vector showing status of key output files}
#'   \item{bagel_results_files}{Vector of files in BAGEL results subdirectory}
#'   \item{ideogram_files}{List with counts of PDF and PNG ideogram files}
#'   \item{missing_files}{Vector of expected files that are missing}
#'
#' @details
#' This function checks for the following types of output files:
#' \itemize{
#'   \item Key analysis matrices and summaries (CSV files)
#'   \item BAGEL analysis report (Markdown file)
#'   \item Saved R data objects
#'   \item BAGEL results subdirectory files
#'   \item Ideogram visualization files (PDF and PNG)
#' }
#'
#' Expected key output files include:
#' \itemize{
#'   \item arm_copynumber_matrix.csv - Copy number calls matrix
#'   \item arm_log2ratio_matrix.csv - Log2 ratio values matrix  
#'   \item arm_copynumber_long.csv - Long format copy number data
#'   \item arm_copynumber_summary.csv - Summary statistics
#'   \item BAGEL_V2_ANALYSIS_REPORT.md - Analysis report
#'   \item demo_bagel_results.RData - Saved analysis results
#' }
#'
#' @examples
#' \dontrun{
#' # Summarize outputs from a BAGEL analysis
#' summary_info <- summarize_bagel_outputs("/path/to/output/directory")
#' 
#' # Check specific file status
#' if (summary_info$key_files_status["arm_copynumber_matrix.csv"]) {
#'   cat("Copy number matrix was generated successfully\n")
#' }
#' 
#' # Silent summary (returns info without printing)
#' summary_info <- summarize_bagel_outputs("/path/to/output", verbose = FALSE)
#' }
#'
#' @export
summarize_bagel_outputs <- function(output_dir, verbose = TRUE) {
  
  if (!dir.exists(output_dir)) {
    stop("Output directory does not exist: ", output_dir)
  }
  
  if (verbose) {
    cat("=== BAGEL Output Files Summary ===\n")
    cat("Output directory:", output_dir, "\n\n")
  }
  
  # Initialize return object
  summary_info <- list(
    total_files = 0,
    key_files_status = logical(),
    bagel_results_files = character(),
    ideogram_files = list(pdf_count = 0, png_count = 0),
    missing_files = character()
  )
  
  # List all output files
  output_files <- list.files(output_dir, recursive = TRUE, full.names = FALSE)
  summary_info$total_files <- length(output_files)
  
  if (verbose) {
    cat("Generated", length(output_files), "output files total\n\n")
  }
  
  # Key output files to check
  key_files <- c(
    "arm_copynumber_matrix.csv",
    "arm_log2ratio_matrix.csv", 
    "arm_copynumber_long.csv",
    "arm_copynumber_summary.csv",
    "BAGEL_V2_ANALYSIS_REPORT.md",
    "bagel_v2_complete_results.RData"
  )
  
  # Check key files status
  key_files_present <- key_files %in% output_files
  names(key_files_present) <- key_files
  summary_info$key_files_status <- key_files_present
  summary_info$missing_files <- key_files[!key_files_present]
  
  # BAGEL results files (in BAGEL_results_* subdirectory)
  bagel_results_dir <- list.dirs(output_dir, recursive = FALSE, full.names = FALSE)
  bagel_results_subdir <- bagel_results_dir[grepl("^BAGEL_results_", bagel_results_dir)]
  
  if (length(bagel_results_subdir) > 0) {
    bagel_subdir_files <- list.files(file.path(output_dir, bagel_results_subdir[1]), full.names = FALSE)
    summary_info$bagel_results_files <- bagel_subdir_files
    
    if (verbose) {
      cat("BAGEL results files (in", bagel_results_subdir[1], "):\n")
      
      expected_bagel_files <- c(
        "analysis_parameters.txt", 
        "arm_level_summaries.txt", 
        "arm_definitions.txt", 
        "gistic_results.txt", 
        "significant_arms.txt", 
        "stringent_calls.txt"
      )
      
      for (file in expected_bagel_files) {
        if (file %in% bagel_subdir_files) {
          file_path <- file.path(output_dir, bagel_results_subdir[1], file)
          file_size <- if (file.exists(file_path)) {
            paste0("(", round(file.size(file_path) / 1024, 1), " KB)")
          } else {
            "(not found)"
          }
          cat("  ✅", file, file_size, "\n")
        } else {
          cat("  ❌", file, "(missing)\n")
          summary_info$missing_files <- c(summary_info$missing_files, 
                                        file.path(bagel_results_subdir[1], file))
        }
      }
      cat("\n")
    }
  }
  
  # Check for ideogram files
  ideogram_dir <- file.path(output_dir, "newly_defined_arms_ideogram")
  if (dir.exists(ideogram_dir)) {
    ideogram_files <- list.files(ideogram_dir, full.names = FALSE)
    
    # Count different file types
    pdf_files <- ideogram_files[grepl("\\.pdf$", ideogram_files)]
    png_files <- ideogram_files[grepl("\\.png$", ideogram_files)]
    
    summary_info$ideogram_files$pdf_count <- length(pdf_files)
    summary_info$ideogram_files$png_count <- length(png_files)
    
    if (verbose) {
      cat("Ideogram files (in newly_defined_arms_ideogram/):\n")
      
      if (length(pdf_files) > 0) {
        individual_chr_pdfs <- length(pdf_files[grepl("chromosome_\\d+", pdf_files)])
        cat("  📊 Individual chromosome PDFs:", individual_chr_pdfs, "files\n")
        
        if (any(grepl("all_chromosomes", pdf_files))) {
          cat("  📊 Combined panel plot: all_chromosomes_ideogram_panel.pdf\n")
        }
      }
      
      if (length(png_files) > 0) {
        cat("  🖼️ PNG versions:", length(png_files), "files\n")
      }
      cat("\n")
    }
  }
  
  # Summary of key files
  if (verbose) {
    cat("Key output files status:\n")
    for (file in key_files) {
      if (file %in% output_files) {
        file_path <- file.path(output_dir, file)
        file_size <- if (file.exists(file_path)) {
          paste0("(", round(file.size(file_path) / 1024, 1), " KB)")
        } else {
          "(not found)"
        }
        cat("  ✅", file, file_size, "\n")
      } else {
        cat("  ❌", file, "(missing)\n")
      }
    }
    
    # Overall summary
    cat("\n=== Summary ===\n")
    cat("Total files:", summary_info$total_files, "\n")
    cat("Key files present:", sum(summary_info$key_files_status), "/", length(key_files), "\n")
    cat("Missing files:", length(summary_info$missing_files), "\n")
    
    if (length(summary_info$missing_files) == 0) {
      cat("🎉 All expected output files are present!\n")
    } else {
      cat("⚠️  Some expected files are missing. Check analysis logs.\n")
    }
  }
  
  invisible(summary_info)
}

#' Check BAGEL Analysis Completeness
#'
#' Quick function to check if a BAGEL analysis completed successfully by
#' verifying the presence of key output files.
#'
#' @param output_dir Character, path to the BAGEL analysis output directory
#' @param required_files Character vector, specific files to check for (optional)
#'
#' @return Logical, TRUE if analysis appears complete, FALSE otherwise
#'
#' @details
#' This function performs a quick completeness check by looking for essential
#' output files. By default, it checks for the arm copy number matrix and
#' analysis report. Additional files can be specified via the required_files
#' parameter.
#'
#' @examples
#' \dontrun{
#' # Quick completeness check
#' if (check_bagel_completeness("/path/to/output")) {
#'   cat("Analysis completed successfully\n")
#' } else {
#'   cat("Analysis may be incomplete\n")
#' }
#' 
#' # Check for specific files
#' custom_files <- c("arm_copynumber_matrix.csv", "gistic_results.txt")
#' check_bagel_completeness("/path/to/output", required_files = custom_files)
#' }
#'
#' @export
check_bagel_completeness <- function(output_dir, required_files = NULL) {
  
  if (!dir.exists(output_dir)) {
    return(FALSE)
  }
  
  # Default required files for basic completeness
  if (is.null(required_files)) {
    required_files <- c(
      "arm_copynumber_matrix.csv",
      "BAGEL_V2_ANALYSIS_REPORT.md"
    )
  }
  
  # Get all output files
  output_files <- list.files(output_dir, recursive = TRUE, full.names = FALSE)
  
  # Check if all required files are present
  all_present <- all(required_files %in% output_files)
  
  return(all_present)
}